spring:
    datasource:
        url: jdbc:postgresql//${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_NAME}
        password: ${PROD_DB_PASSWORD}
        name: spring-blog
    sql:
        init:
            mode: always

matching:
  engine:
    url: ${MATCHING_ENGINE_URL}
    embed-secret: ${MATCHING_ENGINE_EMBED_SECRET}